[package]
name = "AuraChainContracts"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
aptos_framework = "0x1"
# This is our dummy address for compiling, it's fine.
AuraChainContracts = "0x42" 

[dev-addresses]
# Leave this empty

[dependencies.AptosFramework]
# THIS IS THE FIX: We change "devnet" to "mainnet"
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]